// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wnTAhpXtZxbdMJKXu9x6WixqQMJU8xU',
    appId: '1:1045309120591:web:3531c902d927ca28620a3a',
    messagingSenderId: '1045309120591',
    projectId: 'liko-auto',
    authDomain: 'liko-auto.firebaseapp.com',
    storageBucket: 'liko-auto.firebasestorage.app',
    measurementId: 'G-284488FE85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSyuqtD83PBHK-JIoPs3H3XRFSq56ChU',
    appId: '1:1045309120591:android:82b451ac24948bcf620a3a',
    messagingSenderId: '1045309120591',
    projectId: 'liko-auto',
    storageBucket: 'liko-auto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxMAYVALN-fn47O2zk_ozSzEUHewoWy0',
    appId: '1:1045309120591:ios:e0d05b0074752947620a3a',
    messagingSenderId: '1045309120591',
    projectId: 'liko-auto',
    storageBucket: 'liko-auto.firebasestorage.app',
    iosBundleId: 'com.likoauto.lik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxMAYVALN-fn47O2zk_ozSzEUHewoWy0',
    appId: '1:1045309120591:ios:c7e0e1c70ba41b56620a3a',
    messagingSenderId: '1045309120591',
    projectId: 'liko-auto',
    storageBucket: 'liko-auto.firebasestorage.app',
    iosBundleId: 'com.likoauto.l',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5wnTAhpXtZxbdMJKXu9x6WixqQMJU8xU',
    appId: '1:1045309120591:web:31ed2fa33fa6258b620a3a',
    messagingSenderId: '1045309120591',
    projectId: 'liko-auto',
    authDomain: 'liko-auto.firebaseapp.com',
    storageBucket: 'liko-auto.firebasestorage.app',
    measurementId: 'G-149HTH20BY',
  );
}
